-- Casals amb Amics - Seed Data
-- Execute this after schema.sql to populate the database with sample camps.

INSERT INTO camps (name, type, age_range, location_name, address, lat, lng, dates, start_date, end_date, schedule, has_morning_care, has_lunch, has_flexible_pickup, has_transport, has_overnight, cost, services, hobbies, friends, allergy_options, medical_notes, child_rating, survey_count, would_return_percentage, available_places, tags, description, image_color)
VALUES
(
  'Campus Esportiu Montjuïc',
  ARRAY['Esports', 'Aventura'],
  '6-14',
  'Montjuïc, Barcelona',
  'Av. de l''Estadi, 60, 08038 Barcelona',
  41.3641, 2.1567,
  '24 juny - 1 agost',
  '2026-06-24', '2026-08-01',
  '09:00 - 17:00',
  true, true, false, true, false,
  320,
  ARRAY['Menjador', 'Acollida matinal', 'Transport', 'Monitoratge expert'],
  ARRAY['Futbol', 'Natació', 'Bàsquet', 'Atletisme'],
  ARRAY['Pau', 'Laia', 'Marc'],
  ARRAY['Sense gluten', 'Sense lactosa', 'Menú adaptat'],
  'Disposem d''infermeria i protocols per al·lèrgies.',
  4.5, 48, 92, 25,
  ARRAY['Esport', 'Estiu', 'Multiesport'],
  'Campus multiesportiu amb instal·lacions olímpiques. Piscina, pistes i zones verdes.',
  '#0ea5e9'
),
(
  'Casal Creatiu Poblenou',
  ARRAY['Art', 'Música', 'Teatre'],
  '4-12',
  'Poblenou, Barcelona',
  'C/ de la Llacuna, 56, 08005 Barcelona',
  41.4005, 2.2042,
  '26 juny - 31 juliol',
  '2026-06-26', '2026-07-31',
  '09:30 - 16:30',
  true, true, true, false, false,
  280,
  ARRAY['Menjador', 'Acollida matinal', 'Sortida flexible', 'Material inclòs'],
  ARRAY['Dibuix', 'Pintura', 'Música', 'Teatre'],
  ARRAY['Júlia', 'Nil'],
  ARRAY['Sense gluten', 'Vegetarià'],
  'Consultar amb l''organització per al·lèrgies específiques.',
  4.7, 35, 95, 18,
  ARRAY['Art', 'Creativitat', 'Manualitats'],
  'Espai d''expressió artística amb tallers de pintura, música i teatre.',
  '#f59e0b'
),
(
  'Colònies Natura Montseny',
  ARRAY['Natura', 'Colònies', 'Aventura'],
  '8-16',
  'Viladrau, Montseny',
  'Ctra. del Montseny, km 12, 08470 Viladrau',
  41.8478, 2.3902,
  '1 juliol - 15 juliol',
  '2026-07-01', '2026-07-15',
  'Internat 24h',
  false, true, false, true, true,
  580,
  ARRAY['Pensió completa', 'Transport', 'Excursions', 'Monitoratge 24h'],
  ARRAY['Senderisme', 'Escalada', 'Natació', 'Observació d''aus'],
  ARRAY['Arnau', 'Clara', 'Emma', 'Pol'],
  ARRAY['Sense gluten', 'Sense lactosa', 'Fruits secs', 'Menú adaptat'],
  'Menús adaptats a totes les al·lèrgies. Infermeria 24h.',
  4.8, 62, 97, 12,
  ARRAY['Natura', 'Colònies', 'Aventura', 'Excursions'],
  'Colònies al cor del Montseny amb activitats de natura, excursions i convivència.',
  '#22c55e'
),
(
  'STEM Lab Hospitalet',
  ARRAY['Tecnologia', 'Robòtica'],
  '8-15',
  'L''Hospitalet de Llobregat',
  'C/ de la Riera de la Febró, 45, 08902 Hospitalet',
  41.3595, 2.1009,
  '28 juny - 25 juliol',
  '2026-06-28', '2026-07-25',
  '10:00 - 17:00',
  true, true, false, false, false,
  350,
  ARRAY['Menjador', 'Acollida matinal', 'Material tecnològic', 'Ordinadors'],
  ARRAY['Programació', 'Robòtica', 'Ciència', 'Videojocs'],
  ARRAY['Biel', 'Ona'],
  ARRAY['Sense gluten', 'Vegetarià', 'Vegà'],
  'Menjador amb opcions per a dietes especials.',
  4.6, 41, 90, 20,
  ARRAY['Tecnologia', 'Robòtica', 'STEM', 'Programació'],
  'Laboratori tecnològic amb robòtica, programació i experiments científics.',
  '#8b5cf6'
),
(
  'Casal Piscina i Jocs de Gràcia',
  ARRAY['Piscina', 'Esports'],
  '3-10',
  'Gràcia, Barcelona',
  'C/ de la Mare de Déu del Coll, 75, 08023 Barcelona',
  41.4028, 2.1523,
  '25 juny - 2 agost',
  '2026-06-25', '2026-08-02',
  '09:00 - 16:00',
  true, true, true, false, false,
  260,
  ARRAY['Piscina', 'Menjador', 'Acollida matinal', 'Sortida flexible'],
  ARRAY['Natació', 'Jocs aquàtics', 'Manualitats'],
  ARRAY['Martí', 'Sara'],
  ARRAY['Sense gluten', 'Sense lactosa'],
  'Socorristes i personal de vigilància constant.',
  4.4, 53, 88, 30,
  ARRAY['Piscina', 'Jocs', 'Aquàtic'],
  'Casal amb piscina, jocs d''aigua i activitats lúdiques diàries.',
  '#06b6d4'
),
(
  'English Summer Club Sarrià',
  ARRAY['Idiomes', 'Art'],
  '5-14',
  'Sarrià, Barcelona',
  'C/ Major de Sarrià, 125, 08017 Barcelona',
  41.3995, 2.1201,
  '26 juny - 30 juliol',
  '2026-06-26', '2026-07-30',
  '09:30 - 17:00',
  true, true, true, true, false,
  380,
  ARRAY['Menjador', 'Acollida matinal', 'Sortida flexible', 'Transport', 'Professors natius'],
  ARRAY['Anglès', 'Dibuix', 'Cuina', 'Jocs'],
  ARRAY['Max', 'Aina', 'Joan'],
  ARRAY['Sense gluten', 'Sense lactosa', 'Fruits secs', 'Vegetarià', 'Menú adaptat'],
  'Menjador internacional amb opcions per a totes les dietes.',
  4.3, 39, 85, 15,
  ARRAY['Anglès', 'Immersió', 'Idiomes'],
  'Immersió lingüística en anglès amb tallers creatius i jocs.',
  '#ec4899'
),
(
  'Teatre i Música Sants',
  ARRAY['Teatre', 'Música', 'Art'],
  '6-16',
  'Sants, Barcelona',
  'C/ de Sants, 245, 08028 Barcelona',
  41.3754, 2.1365,
  '27 juny - 29 juliol',
  '2026-06-27', '2026-07-29',
  '10:00 - 18:00',
  false, true, true, false, false,
  300,
  ARRAY['Menjador', 'Sortida flexible', 'Instruments', 'Vestuari'],
  ARRAY['Teatre', 'Música', 'Dansa', 'Cant'],
  ARRAY['Roc', 'Mar'],
  ARRAY['Sense gluten'],
  'Cal informar d''al·lèrgies prèviament.',
  4.6, 27, 93, 22,
  ARRAY['Teatre', 'Música', 'Arts escèniques'],
  'Taller d''arts escèniques amb música, teatre i dansa. Funció final al teatre.',
  '#f97316'
),
(
  'Aventura i Mar Maresme',
  ARRAY['Aventura', 'Natura', 'Esports'],
  '7-15',
  'Calella, Maresme',
  'Pg. de la Platja, s/n, 08370 Calella',
  41.6122, 2.6631,
  '1 juliol - 14 agost',
  '2026-07-01', '2026-08-14',
  '09:00 - 17:00',
  true, true, false, true, false,
  340,
  ARRAY['Menjador', 'Acollida matinal', 'Transport', 'Material d''aventura'],
  ARRAY['Caiac', 'Senderisme', 'Natació', 'Escalada', 'Vela'],
  ARRAY['Guillem', 'Marta', 'Hugo', 'Carla'],
  ARRAY['Sense gluten', 'Sense lactosa', 'Fruits secs'],
  'Protocol d''emergències i socorrisme. Farmaciola completa.',
  4.7, 56, 96, 10,
  ARRAY['Mar', 'Aventura', 'Natura', 'Esports aquàtics'],
  'Aventura marinera amb caiac, vela i excursions per la costa del Maresme.',
  '#14b8a6'
);

-- Insert perfil infantil per defecte
INSERT INTO child_profiles (name, age, hobbies)
VALUES ('El meu fill/a', 9, ARRAY['Futbol', 'Natació', 'Robòtica', 'Natura', 'Música']);
